---
title: "Management_graphs"
author: "Sander Devisscher"
date: '2022-08-17'
output: html_document
---

```{r setup, include=FALSE}
library(rgbif)
library(geojsonsf)
library(sf)
library(tidyverse)
```

```{r get credentials}
gbif_email <- Sys.getenv("email")
gbif_pwd <- Sys.getenv("gbif_pwd")
gbif_user <- Sys.getenv("gbif_user")
```

Currently there is only 1 dataset but in the future there will be 2

```{r get data from gbif}
datasetkeys <- c("ea95fd9b-58dc-4e48-b51f-9380e9804607")
taxonkey <- c(2427091)

gbif_downloadKey <- occ_download(pred_in("datasetKey", datasetkeys),
                                 pred("taxonKey", taxonkey),
                                 user = gbif_user,
                                 pwd = gbif_pwd,
                                 email = gbif_email)

occ_download_wait(gbif_downloadKey)
# Execute download request
gbif_download <- occ_download_get(gbif_downloadKey, 
                                  path = tempdir(), 
                                  overwrite = TRUE)

cleanData <- occ_download_import(x = gbif_download) 
```

```{r get verbatim data}
lifeStage_output <- data.frame()
locality_output <- data.frame()

for(d in datasetkeys){
  extractDir <- file.path(tempdir(), "gbifdownload", d)
  utils::unzip(gbif_download[[1]], exdir = extractDir, overwrite = TRUE)
  verbatimFile <- list.files(extractDir, pattern = "verbatim", full.names = TRUE)
  verbatimData <- read.table(file = verbatimFile, sep = "\t", header = TRUE) %>% 
    select(gbifID, lifeStage, verbatimLocality) 
  
  lifeStages <- verbatimData %>% 
    select(gbifID, lifeStage) %>% 
    separate(lifeStage, 
             sep = ";",
             into = c("stage1",
                      "stage2",
                      "stage3",
                      "stage4",
                      "stage5",
                      "stage6",
                      "stage7",
                      "stage8",
                      "stage9",
                      "stage10",
                      "stage11",
                      "stage12",
                      "stage13",
                      "stage14",
                      "stage15",
                      "stage16",
                      "stage17")) %>% 
    pivot_longer(cols = contains("stage"),
                 names_to = "lifestage_nr",
                 values_to = "lifeStage") %>% 
    select(-lifestage_nr) %>% 
    mutate(lifeStage = str_remove(lifeStage, " "),
           lifeStage = str_remove(lifeStage, "lenght:")) %>% 
    separate(lifeStage, sep = ":",
             into = c("lifeStage2",
                      "n")) %>% 
    mutate(n = as.numeric(n)) %>% 
    filter(n != 0,
           !is.na(n)) %>% 
    mutate(lifeStage = case_when(grepl("larvae", lifeStage2) ~ "larvae",
                                 grepl("metamorph", lifeStage2) ~ "juvenile",
                                 grepl("adult", lifeStage2) ~ "adult",
                                 grepl("Juvenieloops", lifeStage2) ~ "juvenile",
                                 gbifID == 1135631008 ~ "larvae",
                                 TRUE ~ lifeStage2)) %>% 
    group_by(gbifID, lifeStage) %>% 
    summarise(n = sum(n, na.rm = TRUE))
  
  if(nrow(lifeStage_output) == 0){
    lifeStage_output <- lifeStages
  }else{
    lifeStage_output <- rbind(lifeStage_output, lifeStages)
  }
  
  localities <- verbatimData %>% 
    select(gbifID, verbatimLocality)
   
  
  if(nrow(locality_output) == 0){
    locality_output <- localities
  }else{
    locality_output <- rbind(locality_output, localities)
  }
}

table(lifeStages$lifeStage, useNA = "ifany")

cleanData <- cleanData %>% 
  select(-lifeStage, -verbatimLocality) %>% 
  left_join(lifeStage_output) %>% 
  left_join(locality_output)
```

```{r data cleaning}
cleanData <- cleanData %>% 
  filter(samplingProtocol != "field observation",
         !grepl("13353", verbatimLocality),
         !grepl("13354", verbatimLocality),
         !grepl("13355", verbatimLocality),
         !grepl("13356", verbatimLocality),
         !grepl("13357", verbatimLocality),
         !grepl("13358", verbatimLocality),
         !grepl("13359", verbatimLocality),
         !grepl("13360", verbatimLocality),
         !grepl("13361", verbatimLocality),
         !grepl("13362", verbatimLocality),
         !grepl("13372", verbatimLocality),
         !grepl("13373", verbatimLocality),
         !is.na(lifeStage))

table(cleanData$verbatimLocality, cleanData$year)
```

```{r add municipality & province}
locations <- cleanData %>% 
  group_by(locationID) %>% 
  summarise(decimalLatitude = first(decimalLatitude),
            decimalLongitude = first(decimalLongitude)) %>% 
  ungroup() %>% 
  filter(locationID != "")

locations <- st_as_sf(locations, 
                      coords = c("decimalLongitude", "decimalLatitude"),
                      crs = 4326)

locations <- st_transform(locations, 4326)

gemeentes <- geojson_sf("../backoffice-wild-analyse/Data/Spatial/Gemeentes.geojson")
gemeentes <- st_transform(gemeentes, 4326)
provincies <- geojson_sf("../backoffice-wild-analyse/Data/Spatial/provinces.geojson")
st_crs(provincies) <- st_crs(31370)
provincies <- st_transform(provincies, 4326)

locations_intersect <- st_intersection(gemeentes, locations)

locations <- locations_intersect %>% 
  mutate(provincie = case_when(NISCODE > 70000 ~ "Limburg",
                               NISCODE > 40000 ~ "Oost-Vlaanderen",
                               NISCODE > 30000 ~ "West-Vlaanderen",
                               NISCODE > 20000 ~ "Vlaams-Brabant",
                               NISCODE > 10000 ~ "Antwerpen",
                               TRUE ~ NA_character_)) %>% 
  select(locationID, NISCODE, NAAM, provincie)

locations <- st_set_geometry(locations, NULL)

cleanData <- cleanData %>% 
  left_join(locations)
```

```{r total individual caught}
total_by_year <- cleanData %>% 
  group_by(year) %>% 
  summarise(n = sum(individualCount, na.rm = TRUE)) %>% 
  ggplot(aes(x = year, y = n)) +
  geom_bar(stat = "identity")
```

```{r total individuals caught by unit of effort}
total_by_year_corrected <- cleanData %>% 
  group_by(year) %>% 
  summarise(effort = n_distinct(eventID),
            n = sum(individualCount, na.rm = TRUE)/effort) 


plot_cpue <- total_by_year_corrected %>% 
  ggplot(aes(x = year, y = n)) +
  geom_bar(stat = "identity") + 
  geom_line(aes(x = year, y = effort),
            stat = "identity") +
  scale_y_continuous(name = "Total catch per unit of effort",
                     sec.axis = sec_axis(trans=~., name="effort"))
```

```{r total individuals caught by lifestage}
total_by_year_by_lifestage <- cleanData %>% 
  group_by(year, lifeStage) %>% 
  summarise(n = sum(individualCount, na.rm = TRUE)) %>% 
  filter(!is.na(lifeStage)) %>% 
  ggplot(aes(x = year, y = n, fill = lifeStage)) +
  geom_bar(stat = "identity",
           position = "stack")
```

```{r capture per unit of effort by lifestage}
total_by_year_corrected_lifestage <- cleanData %>% 
  group_by(year) %>% 
  mutate(effort = n_distinct(eventID)) %>% 
  group_by(year, lifeStage) %>% 
  summarise(effort = max(effort),
            n = sum(n, na.rm = TRUE)/effort) %>% 
  ungroup() %>% 
  add_row(year = 2013,
          lifeStage = "juvenile",
          effort = 213)


plot_cpue_lifestage <- total_by_year_corrected_lifestage %>% 
  ggplot(aes(x = year, y = n, fill = lifeStage)) +
  geom_bar(stat = "identity") + 
  geom_line(aes(x = year, y = effort),
            stat = "identity") +
  scale_y_continuous(name = "Total catch per unit of effort",
                     sec.axis = sec_axis(trans=~., name="effort"))
```

```{r map management}
jaar <- 2018

total_by_year_corrected_gem <- cleanData %>% 
  group_by(year, NISCODE, NAAM) %>% 
  summarise(effort = n_distinct(eventID),
            n = sum(individualCount, na.rm = TRUE)/effort) %>% 
  filter(year == jaar) %>% 
  left_join(gemeentes) %>% 
  ungroup() %>% 
  st_as_sf()

grid <- read_sf("../alien-species-portal/alienSpecies/inst/extdata/grid/be_1km.shp") %>% 
  st_as_sf() %>% 
  st_transform(4326)

spread <- read_sf("../alien-species-portal/alienSpecies/inst/extdata/be_alientaxa_cube.csv") %>% 
  filter(taxonKey == "2427091") %>% 
  filter(year == as.character(jaar)) %>% 
  left_join(grid, by = c("eea_cell_code" = "CELLCODE")) %>% 
  st_as_sf()

library(leaflet)

pal <- colorBin(palette = "RdYlGn",
                domain = total_by_year_corrected_gem$n,
                bins = c(0, 1, 100, 200, 300, 400, 500),
                pretty = TRUE,
                na.color = "#808080",
                reverse = TRUE)

leaflet() %>%
  addPolylines(data = gemeentes,
               weight = 1,
               color = "black") %>% 
  addPolylines(data = provincies, 
               weight = 2,
               color = "black") %>% 
   addPolylines(data = spread, 
               color = "red",
               weight = 1) %>% 
  addPolygons(data = total_by_year_corrected_gem,
              color = ~pal(n)) %>% 
  addLegend(pal = pal,
            values = total_by_year_corrected_gem$n,
            title = "Catch per unit of effort",
            na.label = 0)
```
