---
title: "Ravon artikel 2025"
author: "Sander Devisscher, Teun Everts, Rein Brys"
date: "2025-03-12"
output: html_document
---

```{r}
library(tidyverse)
```

```{r read data}
afvangsten_per_fuik_combined <- read_csv("interim/afvangsten_per_fuik_combined.csv")
```

Staaf grafiek totaal vangsten per jaar
met cumulatieve lijn (op andere as)
en aantal vijvers per jaar als label boven de bar
```{r}
afvangsten_per_fuik_combined %>%
  group_by(Jaar) %>%
  summarise(totaal_vangst = sum(totaal_fuik, na.rm = TRUE),
            aantal_vijvers = n_distinct(locationID)) %>%
  ungroup() %>% 
  mutate(cum_vangst = cumsum(totaal_vangst)) %>% 
  ggplot(aes(x = Jaar, y = totaal_vangst)) +
  geom_bar(aes(fill = "Totale vangst"), 
           stat = "identity") +
  geom_line(aes(y = cum_vangst/4, color = "Cumulatieve vangst"),
            linewidth = 1) +
  geom_text(aes(y = totaal_vangst, label = aantal_vijvers), vjust = -0.5)  +
  scale_y_continuous(
    name = "Totale vangst",
    labels = function(x) paste0(x/1000, "k"),
    sec.axis = sec_axis(~.*4, 
                        name = "Cumulatieve vangst", 
                        labels = function(x) paste0(x/1000, "k"),
                        breaks = seq(0, 500000, by = 100000))
  ) +
  scale_x_continuous(
    limits = c(2009.5, 2024.5),
    breaks = seq(2010, 2024, by = 2)
  ) +
  scale_fill_manual(values = c("Totale vangst" = "#8C8F3A"), 
                    name = "Legenda") + # Naam van de legenda instellen
  scale_color_manual(values = c("Cumulatieve vangst" = "red"),
                     name = "") + # Naam van de legenda instellen
  theme_minimal() +
  theme(legend.position = "bottom", # Legenda onder de grafiek
        legend.title = element_text(hjust = 0.5)) + # Centraal uitlijnen van de legendatitel
  labs(title = "Totale en cumulatieve stierkikker vangst per jaar",
       subtitle = "Aantal beheerde vijvers weergegeven boven elke bar") +
  guides(fill = guide_legend(order = 1), # Volgorde van de legenda items
         color = guide_legend(order = 2)) # Volgorde van de legenda items

  ggsave("./interim/figuren_ravon_artikel/2025/afvangsten_per_fuik_combined.png", width = 10, height = 6, units = "in")
```

